"""Initial migration

Revision ID: 844648698f5a
Revises: 
Create Date: 2025-04-09 12:49:45.638829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844648698f5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(length=30), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_admin_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin'))
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('national_id', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_customers_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('loan_duration', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_loans_customer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loans'))
    )
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=30), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_staffs_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staffs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staffs')
    op.drop_table('loans')
    op.drop_table('customers')
    op.drop_table('admin')
    op.drop_table('users')
    # ### end Alembic commands ###
